### ISSUE TITLE
Possible reference error

### ISSUE THREAD

**Issue by PeterKottas** [i18next/i18next-emoji-postprocessor#2]
## 🐛 Bug Report

A ref error can occur on this line: https://github.com/i18next/i18next-emoji-postprocessor/blob/master/lib/index.js#L32, if key/value is not properly defined. I would recommend changing to 
```
const p = (value || key || '').split(opt.wordSeparator)
```

## To Reproduce

Make a typo in key

## Expected behavior

It should probably return empty string instead of throwing unhandled error.

**Comment by adrai** [comment]
Can you create a PR?

**Comment by PeterKottas** [comment]
PR opened at #3

**Comment by adrai** [comment]
Thanks, released in v1.0.2

---

If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
